# Generated by Django 2.2.6 on 2019-10-18 07:19
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import model_revisioning.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("int", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("boolean", models.BooleanField(default=False)),
                ("null_boolean", models.NullBooleanField()),
                (
                    "hello_world",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Group",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Baz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("int", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ModelOnOtherEndOfRevisionedForeignKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(max_length=255)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ModelOnOtherEndOfRevisionedForeignKeyRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("char", models.CharField(max_length=255)),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.ModelOnOtherEndOfRevisionedForeignKey",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.ModelOnOtherEndOfRevisionedForeignKeyRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithDatabaseConstraint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("one", "One"), ("two", "Two")], max_length=10
                    ),
                ),
                (
                    "foo",
                    model_revisioning.fields.RevisionedForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.ModelOnOtherEndOfRevisionedForeignKey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithMixin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_from_mixin", models.CharField(max_length=100)),
                ("non_mixin_field", models.CharField(max_length=100)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithoutOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithRevisionedForeignKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foo",
                    model_revisioning.fields.RevisionedForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.ModelOnOtherEndOfRevisionedForeignKey",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithUniqueField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_field", models.CharField(max_length=10, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="NonRevisionedModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoftDeleted",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_deleted", models.NullBooleanField(default=False)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="StringRelatedModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="StringRelatedModelRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.StringRelatedModel",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.StringRelatedModelRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="SoftDeletedRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("content", models.TextField()),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.SoftDeleted",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.SoftDeletedRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithUniqueFieldRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("unique_field", models.CharField(max_length=10)),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.ModelWithUniqueField",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.ModelWithUniqueFieldRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithRevisionedForeignKeyRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                (
                    "foo",
                    model_revisioning.fields.RevisionedForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="testapp.ModelOnOtherEndOfRevisionedForeignKeyRevision",
                    ),
                ),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.ModelWithRevisionedForeignKey",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.ModelWithRevisionedForeignKeyRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithoutOptionsRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("content", models.TextField()),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.ModelWithoutOptions",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.ModelWithoutOptionsRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithMixinRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("field_from_mixin", models.CharField(max_length=100)),
                ("non_mixin_field", models.CharField(max_length=100)),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.ModelWithMixin",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.ModelWithMixinRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithDatabaseConstraintRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                (
                    "choice",
                    models.CharField(
                        choices=[("one", "One"), ("two", "Two")], max_length=10
                    ),
                ),
                (
                    "foo",
                    model_revisioning.fields.RevisionedForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="testapp.ModelOnOtherEndOfRevisionedForeignKeyRevision",
                    ),
                ),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.ModelWithDatabaseConstraint",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.ModelWithDatabaseConstraintRevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BazRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.Baz",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.BazRevision",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="BarRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("int", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("boolean", models.BooleanField(default=False)),
                ("null_boolean", models.NullBooleanField()),
                (
                    "hello_world",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Group",
                    ),
                ),
                (
                    "non_revisioned_foreign_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.NonRevisionedModel",
                    ),
                ),
                (
                    "original_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.Bar",
                    ),
                ),
                (
                    "parent_bar",
                    model_revisioning.fields.RevisionedForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="testapp.BarRevision",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.BarRevision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.AddField(
            model_name="bar",
            name="non_revisioned_foreign_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="testapp.NonRevisionedModel",
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="parent_bar",
            field=model_revisioning.fields.RevisionedForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="testapp.Bar",
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="modelwithdatabaseconstraintrevision",
            constraint=models.UniqueConstraint(
                fields=("choice", "foo"), name="one_choice_per_foo"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelwithdatabaseconstraint",
            constraint=models.UniqueConstraint(
                fields=("choice", "foo"), name="one_choice_per_foo"
            ),
        ),
    ]
