# Generated by Django 2.2.5 on 2019-09-21 08:32
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("int", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("boolean", models.BooleanField(default=False)),
                ("null_boolean", models.NullBooleanField()),
                (
                    "hello_world",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Group",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Baz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("int", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithoutOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="NonRevisionedModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SerializedRelatedModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "non_revisioned_foreign_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk",
                        to="testapp.NonRevisionedModel",
                    ),
                ),
                (
                    "non_revisioned_many_to_many",
                    models.ManyToManyField(
                        blank=True, related_name="many", to="testapp.NonRevisionedModel"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SoftDeleted",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_deleted", models.NullBooleanField(default=False)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SoftDeletedRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("content", models.TextField()),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.SoftDeletedRevision",
                    ),
                ),
                (
                    "revision_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.SoftDeleted",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="SerializedRelatedModelRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                (
                    "non_revisioned_foreign_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk",
                        to="testapp.NonRevisionedModel",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.SerializedRelatedModelRevision",
                    ),
                ),
                (
                    "revision_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.SerializedRelatedModel",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ModelWithoutOptionsRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("content", models.TextField()),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.ModelWithoutOptionsRevision",
                    ),
                ),
                (
                    "revision_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.ModelWithoutOptions",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="BazRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.BazRevision",
                    ),
                ),
                (
                    "revision_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.Baz",
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="BarRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("is_head", models.BooleanField(default=False)),
                ("char", models.CharField(blank=True, max_length=255, null=True)),
                ("int", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("boolean", models.BooleanField(default=False)),
                ("null_boolean", models.NullBooleanField()),
                (
                    "hello_world",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Group",
                    ),
                ),
                (
                    "non_revisioned_foreign_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.NonRevisionedModel",
                    ),
                ),
                (
                    "parent_bar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.BarRevision",
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_revisions",
                        to="testapp.BarRevision",
                    ),
                ),
                (
                    "revision_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="testapp.Bar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["revision_at"], "abstract": False},
        ),
        migrations.AddField(
            model_name="bar",
            name="non_revisioned_foreign_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="testapp.NonRevisionedModel",
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="parent_bar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="testapp.Bar",
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
